#!/usr/bin/bash

echo "Starting graphical session..."
export SESSION_STARTED=1

launch_sway() {
		# Gtk
		export GDK_BACKEND=wayland
		export CLUTTER_BACKEND=wayland
		# Qt
		export QT_QPA_PLATFORM=wayland-egl
		export QT_WAYLAND_DISABLE_WINDOWDECORATION="1"
		export QT_AUTO_SCREEN_SCALE_FACTOR=0
		export QT_SCALE_FACTOR=1
		export QT_WAYLAND_FORCE_DPI=96
		# Enlightenment
		export ECORE_EVAS_ENGINE=wayland_egl
		export ELM_ENGINE=wayland_egl
		# SDL
		export SDL_VIDEODRIVER=wayland

		sway
}

galifeu_menu() {
	dialog --nocancel --menu "Choose a desktop environment" 0 0 0\
		kodi ""\
		sway ""\
		nymphcast ""\
		xfce "(with nvidia GPU)"\
		bash ""\
		poweroff ""\
		2>/tmp/session_choice

	#TODO check exit code for ESC

	clear

	case $(cat /tmp/session_choice) in
		kodi)
			startx /usr/bin/kodi
		;;
		sway)
			launch_sway
		;;
		nymphcast)
			startx /opt/nymphcast/nymphcast_server -c /opt/nymphcast/nymphcast_video_config.ini -a /opt/nymphcast/apps/ -w ./Pictures/Wallpapers
		;;
		xfce)
			nvidia-xrun startx
		;;
		bash)
			bash
		;;
		poweroff)
			poweroff
		;;
	esac
}

case $(hostname -s) in
	galifeu)
		galifeu_menu
	;;
	zbox)
		startx
	;;
	*)
		launch_sway
	;;
esac
