#!/bin/bash

__centertext()
{
	local padding=$(( $1 - ${#2} ))
	local before=$(( $padding / 2 ))
	local after=$(( $padding - $before ))
	if [ $before -gt 0 ]; then
		printf ' %.0s' $(seq 1 $before)
	fi
	echo -n $2
	if [ $after -gt 0 ]; then
		printf ' %.0s' $(seq 1 $after)
	fi
	echo ''
}

__errcolor()
{
	LASTERR=$?
	if [ $LASTERR -eq 0 ]; then
		tput setaf 2
	else
		tput setaf 1
	fi
	exit $LASTERR
}

__reset="$(tput sgr0)"
__topcolor="$(tput setab 16)"

__topline()
{
	#TODO cut at end of line if PWD is too long (ellipsis at the start ?)
	path=$(echo $PWD | sed "s/^\/home\/$USER/~/g")
	__centertext $(expr $COLUMNS - 10) $path
}


PS1='\[${__topcolor}$(__errcolor)\]$(__centertext 3 $?)\[${__reset}${__topcolor}\] \A $(__topline)\[${__reset}\]\n\$ '
