theme = "catppuccin_latte"

[editor]
rulers = [80]
bufferline = "multiple"
[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
character = "┊"
render = true

[editor.lsp]
display-messages = true

[editor.whitespace]
[editor.whitespace.characters]
nbsp = "_"
tab = "→"

[editor.whitespace.render]
nbsp = "all"
tab = "all"
tabpad = "·"

[keys]
[keys.insert]
C-backspace = "delete_word_backward"
C-del = "delete_word_forward"
C-left = "move_prev_word_start"
C-right = "move_next_word_end"

[keys.normal]
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
C-t = [":new", ":open ."]
C-w = [":buffer-close"]
S-tab = ":buffer-previous"
del = "delete_char_forward"
tab = ":buffer-next"

[keys.select]
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
